//! Authored expectations, created before adapters. Never regenerated by extraction.
use wtflow_core::{ids, yaml, Entry, Flow, Input, Kind, Node, ResolutionMode, State};
fn main() -> anyhow::Result<()> {
    for (
        lang,
        file,
        owner,
        symbol,
        loop_code,
        if_code,
        loop_line,
        if_line,
        send_line,
        return_line,
        output,
        ty,
        target,
    ) in [
        (
            "typescript",
            "src/control.ts",
            "",
            "control",
            "const item of items",
            "item === \"skip\"",
            "2-5",
            "3",
            "4",
            "6",
            "void",
            "string[]",
            None,
        ),
        (
            "python",
            "control.py",
            "document-ai",
            "control",
            "item in items",
            "item == \"skip\"",
            "2-5",
            "3-4",
            "5",
            "6",
            "None",
            "list[str]",
            Some("send"),
        ),
        (
            "java",
            "src/main/java/demo/Control.java",
            "accounting",
            "Control.control",
            "String item : items",
            "item.equals(\"skip\")",
            "4-7",
            "5",
            "6",
            "8",
            "void",
            "String[]",
            Some("Control.send"),
        ),
    ] {
        let at = |kind, code: &str, line: &str| {
            let mut n = Node::new(kind, code);
            n.src = format!("{file}:{line}");
            n
        };
        let mut each = at(Kind::ForEach, loop_code, loop_line);
        let mut cond = at(Kind::If, if_code, if_line);
        cond.then.push(at(
            Kind::Continue,
            "continue",
            if lang == "python" { "4" } else { if_line },
        ));
        let mut send = at(
            if target.is_some() {
                Kind::Call
            } else {
                Kind::Do
            },
            "send(item)",
            send_line,
        );
        send.target = target.map(str::to_owned);
        each.body = vec![cond, send];
        let mut f = Flow {
            flow: "control".into(),
            version: 1,
            owner: owner.into(),
            trigger: String::new(),
            entry: Entry {
                lang: lang.into(),
                file: file.into(),
                symbol: symbol.into(),
                depth: 0,
            },
            resolution: ResolutionMode::Heuristic,
            fingerprint: String::new(),
            inputs: vec![Input {
                name: "items".into(),
                ty: ty.into(),
            }],
            output: output.into(),
            state: State::default(),
            boundaries: vec![],
            steps: vec![each, at(Kind::Return, "return", return_line)],
        };
        ids::assign(&mut f.steps);
        f.refresh_fingerprint()?;
        std::fs::write(
            format!("testdata/golden/{lang}-control.flow.yaml"),
            yaml::emit(&f)?,
        )?;
    }
    let file = "src/main/java/demo/Routes.java";
    let mut call = Node::new(Kind::Call, "to(\"direct:input\")");
    call.src = format!("{file}:14");
    call.target = Some("Routes@input".into());
    let mut tx = Node::new(Kind::Group, "transacted()");
    tx.src = format!("{file}:14");
    tx.tx = Some("db".into());
    tx.body.push(call);
    let mut f = Flow {
        flow: "events".into(),
        version: 1,
        owner: "accounting".into(),
        trigger: "camel direct:events".into(),
        entry: Entry {
            lang: "java".into(),
            file: file.into(),
            symbol: "Routes@events".into(),
            depth: 0,
        },
        resolution: ResolutionMode::Heuristic,
        fingerprint: String::new(),
        inputs: vec![],
        output: String::new(),
        state: State::default(),
        boundaries: vec![],
        steps: vec![tx],
    };
    ids::assign(&mut f.steps);
    f.refresh_fingerprint()?;
    std::fs::write("testdata/golden/java-camel.flow.yaml", yaml::emit(&f)?)?;
    Ok(())
}
