[package]
name = "wtflow-extract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true

wtflow-core = { path = "../wtflow-core" }
wtflow-resolve = { path = "../wtflow-resolve" }
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
regex.workspace = true
tree-sitter.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-python.workspace = true
tree-sitter-java.workspace = true
rayon.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
criterion.workspace = true
scip.workspace = true
protobuf.workspace = true

[[bench]]
name = "performance"
harness = false
